### ISSUE TITLE
域名ip发生变更后客户端怎么自动更新

### ISSUE THREAD

**Issue by cs0663c** [corkine/wireguard-windows-great-wall-edition#2]
建在动态公网的服务端使用域名解析链接对端 ，当ip发生变化时客户端并不会自动更新域名地址这个有办法解决吗

**Comment by corkine** [comment]
wireguard 里可以直接配 网址:端口，网址使用 DDNS 映射，IP 变化自动更改 DNS，推荐 ddns-go 项目，我自己的服务器就是这样做的动态映射

**Comment by cs0663c** [comment]
我的wg配置了域名和端口用的时大吉 Lucky ddns  客户端在第一次连接上后就认死1个公网ip 除非手动断开重连，这样就会出现服务端更新了ip ，客户端没有更新ip 造成失联

**Comment by corkine** [comment]
这个问题我没有遇到过，推荐定时开启和关闭 wireguard 连接，这样每次连接都会重新解析 dns，安装目录下有个 wg.exe 命令行可以用
